### ISSUE TITLE
The icons are a bit too big

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru_icons.dart#1]
Compared to Material Icons the the YaruIcons of this package are a tiny bit too big :)
Is it something that can be fixed within the conversion to a font? :)

**Comment by Jupi007** [comment]
Indeed they are a bit too big 🤔
I played a bit with the converter but I can't change the default size.
IMO it is related that most yaru icons use the full canvas.

**Comment by Feichtmeier** [comment]
Hm, it is no problem in normal listtiles like in the settings app. However if you use normal menu widgets like navigation rails or bottom bars, the icons sometimes touch the labels

**Comment by Jupi007** [comment]
I'll try to investigate in depth :)
There's indeed something wrong somewhere.

**Comment by Jupi007** [comment]
I found the source of the problem:
Material icons use 24x24 canvas with 2px free padding, Yaru ones are using 16x16 canvas and they use the full canvas without any padding. When transformed to font, the are scaled to 24px and so looks too big (and also even blurry than the default font look).

I'll resize all icons to 24x24 with 2px padding and it should fix the problem.

**Comment by Feichtmeier** [comment]
Awesome, thanks!
