### ISSUE TITLE
[Question] Is it possible to use these icons as font in a vanilla JS site?

### ISSUE THREAD

**Issue by danimesq** [ubuntu/yaru_icons.dart#115]

**Comment by Jupi007** [comment]
Hi @danimesq,
this is absolutely possible, as long as you provide a link to this repo as the original source of icons, and you keep the same license 🙂

**Comment by Jupi007** [comment]
@danimesq I close this issue, but feel free to comment if you need something else :)

**Comment by danimesq** [comment]
@Jupi007, do you have a CSS link to the font?

**Comment by Jupi007** [comment]
Sorry, but this is a flutter package. This mean there is no CSS resource at all.
But you can use the asset files to generate one, with an appropriated tool 🙂
