### ISSUE TITLE
Web search deselects after one character

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru_icons.dart#134]
When searching the web examples on https://ubuntu.github.io/yaru_icons.dart/#/ the search field is deselected after entering one character.

**Comment by Jupi007** [comment]
Yeah, I also noticed it.
I searched a way to fix it without success.
Note that there is the same behaviour in the linux app.

I noticed it after upgrade to flutter 3.7.

**Comment by d-loose** [comment]
I ran into the same issue [here](https://github.com/canonical/firmware-updater/pull/157).
Seems to be caused by this change: https://github.com/flutter/flutter/pull/109702
