### ISSUE TITLE
Rename master to main

### ISSUE THREAD

**Issue by jpnurmi** [ubuntu/yaru_icons.dart#152]
Would it be ok to rename the default branch to `main`? It's been the default for some years - `master` feels a bit old-fashioned now... :)

**Comment by Jupi007** [comment]
It is completely okay 🙂

**Comment by jpnurmi** [comment]
### The default branch has been renamed!

`master` is now named `main`

If you have a local clone, you can update it by running the following commands.

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
