### ISSUE TITLE
SVG icons shifted 1px up?

### ISSUE THREAD

**Issue by elioqoshi** [ubuntu/yaru_icons.dart#159]
![image](https://github.com/ubuntu/yaru_icons.dart/assets/5436686/6ddbeb28-6883-4bc3-b36e-2db35f4e14ce)

All of the icons I noticed are shifted 1px up. Do you know why that's the case? You can see in the example the frame (24px) how the icon is not exactly in the vertical middle.

**Comment by elioqoshi** [comment]
Potentially related to: https://github.com/ubuntu/yaru_icons.dart/issues/77

**Comment by Jupi007** [comment]
Yeah, sorry @elioqoshi the SVGs from this repo are all applying this workaround of 1px up shift.
But I just thought that I should automate this into a script, so the source files are clean.

**Comment by elioqoshi** [comment]
@Jupi007 I already fixed them in the Figma library but it would be great to have the sources fixed!

btw, do you know the origin of the icons originally?

**Comment by Jupi007** [comment]
@elioqoshi I'm currently very very busy, but I'll ping you once I fixed the source files.

> btw, do you know the origin of the icons originally?

Most of the icons has been converted by myself from a 16x16 canvas to the 24x24 one used by flutter, from the yaru theme repository itself.
But I also created a part of them from scratch (ex: the radio one).

**Comment by elioqoshi** [comment]
This is not urgent, I already fixed them in our design library in Figma. I was mostly curious who the creator of the complete icon set is?

**Comment by Jupi007** [comment]
@elioqoshi You can find the original authors here (the suru icon set): https://github.com/ubuntu/yaru/blob/master/icons/AUTHORS
But then the yaru community extended it a lot, so there isn't a "creator" by itself as it is a community work.
