### ISSUE TITLE
Unusual import path

### ISSUE THREAD

**Issue by jpnurmi** [ubuntu/yaru_icons.dart#25]
Could you consider adjusting the import path to how it's in a majority of Dart packages, please?

```dart
import yaru_icons/yaru_icons.dart
```
vs.
```dart
import yaru_icons/widgets/yaru_icons.dart
```

I'm asking because it often happens to me that I keep hitting the `pub get` shortcut and wondering why the import fails even though the dependency is there...

https://user-images.githubusercontent.com/140617/142381741-95ff9f11-9cbc-470f-bf61-67dab83a250c.mp4

**Comment by jpnurmi** [comment]
Why not have the font file in `assets/` outside of `lib/`? It's not something users import, right?

- `lib/widgets/yaru_icons.dart` -> `lib/yaru_icons.dart`
- `lib/icon_font/ui_icons.ttf` -> `assets/ui_icons.ttf`

**Comment by jpnurmi** [comment]
Actually, even better to add `lib/yaru_icons.dart` that exports the existing `lib/widgets/yaru_icons.dart` to avoid breaking anyone's code:

**lib/yaru_icons.dart:**
```dart
/// Library level docs ;)
library yaru_icons;

export 'widgets/yaru_icons.dart'
```

**Comment by jpnurmi** [comment]
Simpler packages tend to take a shortcut and put the whole implementation in `package/lib/package.dart`, but once the complexity grows, this kind of structure is recommended:
```
package
|__ lib
    |__ src
    |   |__ foo.dart
    |   |__ bar.dart
    |__ package.dart
```
The top-level `package.dart` defines the library, and exports the selected symbols from `src/*.dart`. Technically, it's possible to import e.g. `package/src/foo.dart` in user code, those are considered implementation details: https://dart.dev/tools/linter-rules#implementation_imports.

**Comment by jpnurmi** [comment]
(The proposed structure would be close to the recommended structure except that `src` would be called `widgets`, which is not important and probably not worth renaming at the cost of breaking existing imports...)

**Comment by Jupi007** [comment]
No problem, I'll do the change today :)

**Comment by Feichtmeier** [comment]
> 
> 
> (The proposed structure would be close to the recommended structure except that `src` would be called `widgets`, which is not important and probably not worth renaming at the cost of breaking existing imports...)

Let's just do it right now (with the src dir) and then we can relax. As I said, only some apps use yaru_icons.dart currently, so two PRs and everything is back to normal.
