### ISSUE TITLE
Request: Tree Icon

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru_icons.dart#38]
@Jupi007 could you eventually add a plant and / or tree icon? 

The material icon looks so weird
![grafik](https://user-images.githubusercontent.com/15329494/161636587-22707b93-5dc2-4a5d-9be1-0a7d1c6c57b9.png)

:)

**Comment by Jupi007** [comment]
Ofc, I'll do it tomorrow :)

**Comment by Feichtmeier** [comment]
Thank you!
