### ISSUE TITLE
Icon request: snap, debian and flatpak

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru_icons.dart#43]
It would be lovely if we could have snap, debian and flatpak symbolics inside yaru_icons.dart

I could use it for the software project :)
![grafik](https://user-images.githubusercontent.com/15329494/168491144-2dd5b884-7660-4aeb-b9d2-3cc1798dbbf4.png)

**Comment by Jupi007** [comment]
Ofc, good idea. I'll do it.

That's strange but I didn't get the notification for this issue 🤔
