### ISSUE TITLE
Icon Request: open app

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru_icons.dart#51]
It would be useful for the software app dialog, as I think an elevated button "open" is too noisy here

![grafik](https://user-images.githubusercontent.com/15329494/171337253-fb8610f8-c492-438c-8a78-89f426ab71f4.png)

maybe a combinnation of view-restore the upper arrow and fullscreen :)

**Comment by Jupi007** [comment]
Okay, I'll add it :+1:
