### ISSUE TITLE
Animated icons paths overlap when using transparent color

### ISSUE THREAD

**Issue by Jupi007** [ubuntu/yaru_icons.dart#62]
See https://github.com/ubuntu-flutter-community/software/pull/233

**Comment by Jupi007** [comment]
All animated icons are affected:

![image](https://user-images.githubusercontent.com/36476595/190972046-74ef99bc-728a-45d7-b609-685b2797113f.png)

**Comment by Feichtmeier** [comment]
😢 oh I am sorry to hear this
Alternativly you could go back to the first iteration?

**Comment by Jupi007** [comment]
Not even sadly, the problem is related to the overlap paths (I was already using in the first iteration).
