### ISSUE TITLE
Icon search

### ISSUE THREAD

**Issue by jpnurmi** [ubuntu/yaru_icons.dart#70]
There used to be a way to browse the icons with their names in a searchable way but now README.md links to the web app that previews the icons without listing their names in a searchable way.

![image](https://user-images.githubusercontent.com/140617/197385577-6d31a858-6f4e-45eb-b43e-45d72dd9e978.png)

**Comment by Feichtmeier** [comment]
Yeah, we would need some kind of mapping to combine both web view and this table. I changed it in
https://github.com/ubuntu/yaru_icons.dart/commit/2bd8058ae1791d1d64d434b9cf25bce790f763ba

**Comment by Feichtmeier** [comment]
https://github.com/ubuntu/yaru_icons.dart/blob/master/doc/icon_list.md

**Comment by Jupi007** [comment]
That would be a really nice!
