### ISSUE TITLE
Icon request: switch/toggle

### ISSUE THREAD

**Issue by jpnurmi** [ubuntu/yaru_icons.dart#73]
https://github.com/ubuntu/yaru_widgets.dart/pull/335

**Comment by Jupi007** [comment]
What kind of design should I use?
Material or gnome-like?

Because our checkboxes icons are using the look from gtk (checkmark + border geometry).

**Comment by jpnurmi** [comment]
How about the kind of design you plan for https://github.com/ubuntu/yaru_widgets.dart/issues/202 in the future?

**Comment by jpnurmi** [comment]
The icon will be used in the yaru_widgets.dart example. There's a temporary one made with two containers. :)

![image](https://user-images.githubusercontent.com/140617/197610338-74bdfe73-d0ce-41d4-9e3a-526ac5e6f5f7.png)

**Comment by Feichtmeier** [comment]
Ah I need to work on the 3.4 PR again, there are the new switches, which look much more like in gnome

**Comment by Jupi007** [comment]
Okay, so I'll have a go with a gtk4 like look :)
