### ISSUE TITLE
Icon request: standard device icons

### ISSUE THREAD

**Issue by d-loose** [ubuntu/yaru_icons.dart#80]
I'd like to cover all [standard device icons](https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html#devices) in the firmware updater. Some icons are still missing or follow a different naming scheme. Currently we're still [manually mapping](https://github.com/canonical/firmware-updater/blob/f1934c6f56c8ee7d6480d8ed4a5b61f0168be2e2/lib/src/widgets/device_icon.dart#L4) the standard icon names to appropriate Yaru icons if they differ. Would it be possible to rename some existing icons or provide alternative names for the same icon?

- audio-card (-> audio, should have a dedicated icon imo)
- ~~audio-input-microphone (-> microphone)~~
- ~~battery (-> battery_level_100)~~
- [camera_web](https://github.com/canonical/firmware-updater/issues/125) (missing)
- modem (missing but probably irrelevant in 2022 :D)
- ~~pda (-> smartphone)~~
- scanner (missing)
- ~~video-display (-> desktop_display)~~

**Comment by Jupi007** [comment]
Hi @d-loose,
I will add the missing icons :)

And I think it is a really good idea to rename icon names to something better and consistent :+1:
Just, can you open a separate issue for this?
I'd like to do this in two time: add missing device icons, then do a big renaming (which will require to bump to a major version).

Thanks :)

**Comment by d-loose** [comment]
Yes, of course - thanks! :)
