### ISSUE TITLE
Provide standard names icons

### ISSUE THREAD

**Issue by d-loose** [ubuntu/yaru_icons.dart#81]
- [x] #99
- [x] #103
- [x] #104

**Comment by Jupi007** [comment]
TODO list:

- [ ] simplify all icon names as much as possible, like `checkbox-button` -> `checkbox`, so we can have intuitive names to use ;
- [ ] add missing freedesktop icons with simpler names ;
- [ ] use symlinks to link simple icon names to freedesktop compliant ones.

The symlinks feature should be added in the tool by this PR: (https://github.com/ScerIO/icon_font_generator/pull/27).

**Comment by Jupi007** [comment]
Closed by #99 #103 #104
